index_name: context_store
settings:
  number_of_shards: 1
  number_of_replicas: 0
mappings:
  properties:
    id:
      type: keyword
    type:
      type: keyword
    title:
      type: text
    content:
      type: text
    tags:
      type: keyword
    created_at:
      type: date
    metadata:
      type: object
      properties:
        source:
          type: keyword
        format:
          type: keyword
        language:
          type: keyword
        # Additional metadata fields can be added here
    key_points:
      type: text  # Optional for sessions
    next_steps:
      type: text  # Optional for sessions
